### PR TITLE
#75 update & center social media icons

### LINKED ISSUE #75: Defect: Major:  Social media links opens in same window & Footer links sequence is incorrect
Steps:
1. Navigate to https://2-footer--vg-macktrucks-com--hlxsites.hlx.page/
2. Validate the footer

Expected:
image

Actual:
1. Social media links opens in the same window unlike in new window 
2. Links in the footer are not in correct sequence as expected.
3. Facebook logo is not as expected 

image

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
I have to update fontawesome to v4 and remove the console errors related to the missing social media icons svg files, which are now all centred and with the correct icon version. Also, I restore the gap in the links section

Fix #75

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://75-social-media-links-footer--vg-macktrucks-com--hlxsites.hlx.page/

### CODE REVIEW

**Comment by jonatan-lledo-netcentric** [comment]
merge 1st the PR #71 of eloqua form before and I'll update it with a few fixes in footer block that I made here

**Review by Lakshmishri — CHANGES_REQUESTED** [review]
Are we not addressing link should open in new window?

**Comment by jonatan-lledo-netcentric** [comment]
> Are we not addressing link should open in new window?

fixed, now social links have target _blank

**Comment by jonatan-lledo-netcentric** [comment]
Also, I refactor the innerHTML to use a fragment (based on the code that is in the sub-nav block) to avoid its use and be safer.

**Review by SantiagoHomps-NC — APPROVED** [review]

**Review by Lakshmishri — APPROVED** [review]

**Pull request merged**
